### ISSUE TITLE
bin/docx2csv is not executable

### ISSUE THREAD

**Issue by K4zuki** [ivbeg/docx2csv#4]
### Condition

- MacOS
- Python 2.7, 3.6

### Problem

- `docx2csv` is not executable(a permission error occurs)

```bash
$ /usr/local/bin/docx2csv

bash: /usr/local/bin/docx2csv: Permission denied
```

### How to confirm

```bash 
$ ls -l `which docx2csv`

-rw-r--r--  1 yamamoto  admin  1177 Dec 13 21:13 /usr/local/bin/docx2csv
```

---
- Simple `chmod +x bin/docx2csv` would fix the issue

**Comment by leedoyle** [comment]
Other way would be 'python3 /usb/local/bin/docx2csv $filepath'

**Comment by ivbeg** [comment]
Replaced `docx2csv` script to same name entry point in doc2csv/__main__.py. It could be called as `docx2csv` or `python -m docx2csv`
