### ISSUE TITLE
TypeError: extract() got an unexpected keyword argument 'output'

### ISSUE THREAD

**Issue by Reventh** [ivbeg/docx2csv#9]
Hi @ivbeg

I tried using this module. However, I am getting a TypeError. Please can you let me know, what's causing this issue.

**Comment by ivbeg** [comment]
> 
> 
> Hi @ivbeg
> 
> I tried using this module. However, I am getting a TypeError. Please can you let me know, what's causing this issue.

Please provide info about Python version and example .docx file

**Comment by Reventh** [comment]
Hi @ivbeg 

Thank you for your time for looking in to this. Here is the below example that I used to convert a docx in to xlsx and received the above error 

```
from docx2csv import extract_tables, extract
extract(filename='C:\\xxx\\xxxx\\xxx\\xx xx xxxxx_ xx_xxc xx.docx', format="xlsx", output='HC_LS.xlsx')
```

**version**:Python3
used in Jupyter notebooks

Thank you in advance.

**Comment by ivbeg** [comment]
Please provide an example .docx file or try this one.
[example.docx](https://github.com/ivbeg/docx2csv/files/5696524/example.docx)

**Comment by Reventh** [comment]
After using the above docx , I received the same error.

**Comment by ivbeg** [comment]
Please provide full trace of error, not just error name

**Comment by ivbeg** [comment]
Closed due inactivity
